#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

admin_create_program:
  path: "/admin/program/create"
  controller: 'App\Controller\AdminController::createProgram'

program_submission:
  resource: App\Controller\ProgramSubmissionController
  type: annotation
